### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by SamB440** [Kowagatte/Damocles#3]
Hello there,

I understand you're not working on this plugin anymore, however I was wondering if you still had the resourcepack? The link on your Spigot resource no longer works.

**Comment by Kowagatte** [comment]
I do still have it. I'm currently at class. Will upload it when I get home.

**Comment by Kowagatte** [comment]
https://www.dropbox.com/s/u7t692wbmhtukvp/Damocles%20Resource%20Pack.rar?dl=0

**Comment by SamB440** [comment]
Thank you, it works :+1: Currently coding on top of the current plugin and I'll probably use it on my server. Pretty cool what you did.
